create table if not exists public.retrieval_runs (
  id bigint generated by default as identity primary key,
  triggered_by text not null default 'system',
  client_scope text,
  status text not null default 'running',
  notes text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.curated_stories (
  id bigint generated by default as identity primary key,
  story_fingerprint text not null unique,
  client_id text not null,
  client_name text not null,
  section text not null check (section in ('human', 'realtime')),
  canonical_url text,
  source_domain text,
  title text not null,
  person_or_subject text,
  person_descriptor text,
  event_or_subject text,
  summary text not null,
  why_it_fits text,
  why_could_go_viral text,
  lesson text,
  urgency text,
  platform_hint text,
  published_at timestamptz,
  source_urls_json jsonb not null default '[]'::jsonb,
  status text not null default 'ready',
  retrieval_run_id bigint references public.retrieval_runs(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists curated_stories_client_section_idx
  on public.curated_stories (client_id, section, status);

create index if not exists curated_stories_published_idx
  on public.curated_stories (published_at desc);

alter table public.retrieval_runs enable row level security;
alter table public.curated_stories enable row level security;

create policy "service role full access retrieval runs"
on public.retrieval_runs
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create policy "service role full access curated stories"
on public.curated_stories
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
